baseURL = 'https://example.org/'
title = 'LYRIFY'
theme = 'my theme'

defaultContentLanguage = "en"

[languages]
  [languages.en]
    locale = "en-US"

[security]
allowContent = ['.*']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
album = "albums"
artist = "artists"