baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LYRIFY'
theme = 'my theme'

[security]
allowContent = ['.*']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
album = "albums"
artist = "artists"