baseURL = 'https://example.org/'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Artists'
    pageRef = '/artists/_index'
    weight = 20

  [[menus.main]]
    name = 'Albums'
    pageRef = '/albums/_index'
    weight = 30

  [[menus.main]]
    name = 'Contact'
    pageRef = '/pages/contact'
    weight = 40

  [[menus.main]]
    name = 'Privacy Policy'
    pageRef = '/pages/privacy-policy'
    weight = 50
  
  [[menus.main]]
    name = 'Disclaimer'
    pageRef = '/pages/disclaimer'
    weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
